/**
 * WARNING: Generated code! do not change!
 * Generated by: go/IEntityDAO.ftl
 */
package entity

import (
	"github.com/quintans/taskboard/common/entity"
)

type IBoardDAO interface {
	Delete(entity *entity.Board) error
    DeleteById(id int64) (bool, error)
    DeleteByIdAndVersion(id int64, version int64) error
    Save(entity *entity.Board) error
    FindById(id int64) (*entity.Board, error)
    FindAll() ([]*entity.Board, error)
    FindByName(name *string) (*entity.Board, error)
    FindByDescription(description *string) (*entity.Board, error)
}
