/**
 * WARNING: Generated code! do not change!
 * Generated by: go/IEntityDAO.ftl
 */
package entity

import (
	"github.com/quintans/taskboard/common/entity"
)

type INotificationDAO interface {
	Delete(entity *entity.Notification) error
    DeleteById(id int64) (bool, error)
    DeleteByIdAndVersion(id int64, version int64) error
    Save(entity *entity.Notification) error
    FindById(id int64) (*entity.Notification, error)
    FindAll() ([]*entity.Notification, error)
}
