/**
 * WARNING: Generated code! do not change!
 * Generated by: go/IEntityDAO.ftl
 */
package entity

import (
	"github.com/quintans/taskboard/common/entity"
)

type IRoleDAO interface {
	Delete(entity *entity.Role) error
    DeleteById(id int64) (bool, error)
    DeleteByIdAndVersion(id int64, version int64) error
    Save(entity *entity.Role) error
    FindById(id int64) (*entity.Role, error)
    FindAll() ([]*entity.Role, error)
    FindByUserKind(userId *int64, kind string) (*entity.Role, error)
}
