/**
 * WARNING: Generated code! do not change!
 * Generated by: go/IEntityDAO.ftl
 */
package entity

import (
	"github.com/quintans/taskboard/common/entity"
)

type ITaskDAO interface {
	Delete(entity *entity.Task) error
    DeleteById(id int64) (bool, error)
    DeleteByIdAndVersion(id int64, version int64) error
    Save(entity *entity.Task) error
    FindById(id int64) (*entity.Task, error)
    FindAll() ([]*entity.Task, error)
    FindByPos(laneId *int64, position *int64) (*entity.Task, error)
}
