/**
 * WARNING: Generated code! do not change!
 * Generated by: go/IEntityDAO.ftl
 */
package entity

import (
	"github.com/quintans/taskboard/common/entity"
)

type IUserDAO interface {
	Delete(entity *entity.User) error
    DeleteById(id int64) (bool, error)
    DeleteByIdAndVersion(id int64, version int64) error
    Save(entity *entity.User) error
    FindById(id int64) (*entity.User, error)
    FindAll() ([]*entity.User, error)
    FindByActiveUser(username *string, dead *int64) (*entity.User, error)
}
