/**
 * Warning: Generated code! do not change!
 * Generated by: go/AppCtx.ftl
 */
package impl

import (
	"github.com/quintans/toolkit/web"
	"github.com/quintans/taskboard/go/service"
	"net/http"
	"github.com/quintans/goSQL/db"
)

func NewAppCtx(w http.ResponseWriter, r *http.Request) *AppCtx {
	this := new(AppCtx)
	this.Context = new(web.Context)
	this.Init(this, w, r)
	this.TaskBoardServiceFactory = NewTaskBoardService
	return this
}

type AppCtx struct {
	*web.Context
	
	Store db.IDb
	taskBoardService service.ITaskBoardService
	TaskBoardServiceFactory func(appCtx *AppCtx) service.ITaskBoardService
}

func (this *AppCtx) AsPrincipal() Principal {
	return this.Principal.(Principal)
}

func (this *AppCtx) GetTaskBoardService() service.ITaskBoardService {
	if this.taskBoardService == nil {
		// will GC collect this circular reference?? 
		this.taskBoardService = this.TaskBoardServiceFactory(this)
	}
	return this.taskBoardService
}

func (this *AppCtx) BuildJsonRpc(transaction func(ctx web.IContext) error) *web.JsonRpc {
	// JSON-RPC services
	var svc *web.Service
	var act *web.Action
	json := web.NewJsonRpc(nil) // json-rpc resgistry

	// JSON Vulnerability Protection.
	// AngularJS will automatically strip the prefix before processing it as JSON.
	jsonpProtection := func(ctx web.IContext) error {
		url := ctx.GetRequest().URL.Path
		logger.Debugf("===>> entering %s", url)
		err := ctx.Proceed()
		logger.Debugf("<<=== exiting %s", url)
		// this must be written after because cookies might be set (ex: Login)
		if err == nil {
			ctx.GetResponse().Write([]byte(")]}',\n"))
		}
		return err
	}
	
	svc = json.RegisterAs("taskboard", this.GetTaskBoardService())
	act = svc.GetAction("WhoAmI")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	act = svc.GetAction("FetchBoardUsers")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	act = svc.GetAction("FetchBoardAllUsers")
	act.PushFilterFunc(transaction, authorize("ADMIN"), jsonpProtection)
	act = svc.GetAction("FetchBoards")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	act = svc.GetAction("FetchBoardById")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	act = svc.GetAction("FullyLoadBoardById")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	act = svc.GetAction("SaveBoard")
	act.PushFilterFunc(transaction, authorize("ADMIN"), jsonpProtection)
	act = svc.GetAction("DeleteBoard")
	act.PushFilterFunc(transaction, authorize("ADMIN"), jsonpProtection)
	act = svc.GetAction("AddLane")
	act.PushFilterFunc(transaction, authorize("ADMIN"), jsonpProtection)
	act = svc.GetAction("SaveLane")
	act.PushFilterFunc(transaction, authorize("ADMIN"), jsonpProtection)
	act = svc.GetAction("DeleteLastLane")
	act.PushFilterFunc(transaction, authorize("ADMIN"), jsonpProtection)
	act = svc.GetAction("SaveUser")
	act.PushFilterFunc(transaction, authorize("ADMIN"), jsonpProtection)
	act = svc.GetAction("FetchUsers")
	act.PushFilterFunc(transaction, authorize("ADMIN"), jsonpProtection)
	act = svc.GetAction("DisableUser")
	act.PushFilterFunc(transaction, authorize("ADMIN"), jsonpProtection)
	act = svc.GetAction("AddUserToBoard")
	act.PushFilterFunc(transaction, authorize("ADMIN"), jsonpProtection)
	act = svc.GetAction("RemoveUserFromBoard")
	act.PushFilterFunc(transaction, authorize("ADMIN"), jsonpProtection)
	act = svc.GetAction("SaveUserName")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	act = svc.GetAction("ChangeUserPassword")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	act = svc.GetAction("SaveTask")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	act = svc.GetAction("MoveTask")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	act = svc.GetAction("FetchNotifications")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	act = svc.GetAction("SaveNotification")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	act = svc.GetAction("DeleteNotification")
	act.PushFilterFunc(transaction, authorize("USER"), jsonpProtection)
	return json
}

func authorize(roles ...string) func(ctx web.IContext) error {
	return func(ctx web.IContext) error {
		user := ctx.GetPrincipal().(Principal)
		for _, r := range roles {
			for _, role := range user.Roles {
				if r == string(role) {
					if err := ctx.Proceed(); err != nil {
						return err
					}
					return nil
				}
			}
		}
		http.Error(ctx.GetResponse(), "Unauthorized", http.StatusUnauthorized)
		return nil
	}
}
