/**
 * WARNING: Generated code! do not change!
 * Generated by: go/DTO.ftl
 */
package dto

import (
	"github.com/quintans/toolkit/web/app"
)

func NewBoardSearchDTO() BoardSearchDTO {
	this := BoardSearchDTO{}
	return this
}

type BoardSearchDTO struct {
	app.Criteria
	
	Name *string `json:"name"`
}
