/**
 * WARNING: Generated code! do not change!
 * Generated by: go/DTO.ftl
 */
package dto

import (
	"github.com/quintans/toolkit/web/app"
)

func NewBoardUserSearchDTO() BoardUserSearchDTO {
	this := BoardUserSearchDTO{}
	return this
}

type BoardUserSearchDTO struct {
	app.Criteria
	
	BoardId int64 `json:"boardId"`
	Name *string `json:"name"`
}
