/**
 * WARNING: Generated code! do not change!
 * Generated by: go/DTO.ftl
 */
package dto

import (
)

func NewIdentityDTO() IdentityDTO {
	this := IdentityDTO{}
	return this
}

type IdentityDTO struct {
	Id *int64 `json:"id"`
	Name *string `json:"name"`
	Roles []*string `json:"roles"`
}
