/**
 * WARNING: Generated code! do not change!
 * Generated by: go/DTO.ftl
 */
package dto

import (
	"github.com/quintans/toolkit/web/app"
)

func NewNotificationSearchDTO() NotificationSearchDTO {
	this := NotificationSearchDTO{}
	return this
}

type NotificationSearchDTO struct {
	app.Criteria
	
	TaskId *int64 `json:"taskId"`
	Email *string `json:"email"`
}
