/**
 * WARNING: Generated code! do not change!
 * Generated by: go/DTO.ftl
 */
package dto

import (
)

func NewUserDTO() UserDTO {
	this := UserDTO{}
	return this
}

type UserDTO struct {
	IdVersionDTO
	
	Name *string `json:"name"`
	Username *string `json:"username"`
	Password *string `json:"password"`
	Admin bool `json:"admin"`
}
