/**
 * Warning: Generated code! do not change!
 * Generated by: go/EntityDB.ftl
 */
package entity;

import (
	"github.com/quintans/goSQL/db"
)

var (
	BOARD = db.TABLE("BOARD")
	BOARD_C_ID = BOARD.KEY("ID")
	BOARD_C_VERSION = BOARD.VERSION("VERSION")
	// Audit
	BOARD_C_CREATION = BOARD.COLUMN("CREATION")
	BOARD_C_MODIFICATION = BOARD.COLUMN("MODIFICATION")
	// Atributos 
	BOARD_C_NAME = BOARD.COLUMN("NAME")
	BOARD_C_DESCRIPTION = BOARD.COLUMN("DESCRIPTION")
	//FK's
	BOARD_A_LANES = BOARD.
				ASSOCIATE(BOARD_C_ID).TO(LANE_C_BOARD_ID).
				As("Lanes")
)
