/**
 * Warning: Generated code! do not change!
 * Generated by: go/EntityDB.ftl
 */
package entity;

import (
	"github.com/quintans/goSQL/db"
)

var (
	LANE = db.TABLE("LANE")
	LANE_C_ID = LANE.KEY("ID")
	LANE_C_VERSION = LANE.VERSION("VERSION")
	// Audit
	LANE_C_CREATION = LANE.COLUMN("CREATION")
	LANE_C_MODIFICATION = LANE.COLUMN("MODIFICATION")
	// Atributos 
	LANE_C_NAME = LANE.COLUMN("NAME")
	LANE_C_POSITION = LANE.COLUMN("POSITION")
	LANE_C_BOARD_ID = LANE.COLUMN("BOARD").As("BoardId")
	//FK's
	LANE_A_BOARD = LANE.
				ASSOCIATE(LANE_C_BOARD_ID).TO(BOARD_C_ID).
				As("Board")
	LANE_A_TASKS = LANE.
				ASSOCIATE(LANE_C_ID).TO(TASK_C_LANE_ID).
				As("Tasks")
	LANE_A_NOTIFICATIONS = LANE.
				ASSOCIATE(LANE_C_ID).TO(NOTIFICATION_C_LANE_ID).
				As("Notifications")
)
