/**
 * WARNING: Generated code. Changes will be overwritten.
 * Generated by: go/ServiceOperationIn.ftl
 */
package service


type MoveTaskIn struct {
	TaskId int64 `json:"taskId"`
	LaneId int64 `json:"laneId"`
	// position = -1 is to eliminate
	Position int64 `json:"position"`
}
