/**
 * WARNING: Generated code! do not change!
 * Generated by: go/DTO.ftl
 */
package dto

import (
	"github.com/quintans/toolkit/ext"
)

func NewIdVersionDTO() IdVersionDTO {
	this := IdVersionDTO{}
	this.Version = ext.Int64Ptr(1)
	return this
}

type IdVersionDTO struct {
	Id *int64 `json:"id"`
	Version *int64 `json:"version"`
}
