/**
 * WARNING: Generated code! do not change!
 * Generated by: go/DTO.ftl
 */
package dto

import (
)

func NewLoginDTO() LoginDTO {
	this := LoginDTO{}
	return this
}

type LoginDTO struct {
	Username *string `json:"username"`
	Password *string `json:"password"`
}
