/**
 * WARNING: Generated code! do not change!
 * Generated by: go/DTO.ftl
 */
package dto

import (
	"github.com/quintans/toolkit/web/app"
)

func NewUserSearchDTO() UserSearchDTO {
	this := UserSearchDTO{}
	return this
}

type UserSearchDTO struct {
	app.Criteria
	
	Name *string `json:"name"`
}
