/**
 * WARNING: Generated code! do not change!
 * Generated by: go/EntityDAOBase.ftl
 */
package impl

import (
	"github.com/quintans/taskboard/common/entity"
	T "github.com/quintans/taskboard/biz/tables"
	"github.com/quintans/toolkit/web/app"
	coll "github.com/quintans/toolkit/collection"
)

type BoardDAOBase struct {
	Context *AppCtx
}

func (this BoardDAOBase) Delete(entity *entity.Board) error {
	store := this.Context.Store
	return app.Delete(store, T.BOARD, entity)
}
	
func (this BoardDAOBase) DeleteById(id int64) (bool, error) {
	store := this.Context.Store
	return app.DeleteById(store, T.BOARD, id)
}

func (this BoardDAOBase) DeleteByIdAndVersion(id int64, version int64) error {
	store := this.Context.Store
	return app.DeleteByIdAndVersion(store, T.BOARD, id, version)
}
    
func (this BoardDAOBase) Save(entity *entity.Board) error {
	store := this.Context.Store
	return app.Save(store, T.BOARD, entity)
}

func (this BoardDAOBase) FindById(id int64) (*entity.Board, error) {
	entity := entity.NewBoard()
	store := this.Context.Store
	ok, err := app.FindById(store, T.BOARD, entity, id)
	if ok {
		return entity, nil
	}
	return nil, err
}

func ConvertToBoard(list coll.Collection) []*entity.Board {
	// converts the list to an array
	entities := make([]*entity.Board, list.Size(), list.Size())
	i := 0
	for e := list.Enumerator(); e.HasNext(); i++ {
		entities[i] = e.Next().(*entity.Board)
	}
	return entities
}

func (this BoardDAOBase) FindAll() ([]*entity.Board, error) {
	typ := (*entity.Board)(nil)
	store := this.Context.Store
	list, err := app.FindAll(store, T.BOARD, typ)
	if err != nil {
		return nil, err
	}
	entities := ConvertToBoard(list)
	return entities, nil
}
    
func (this BoardDAOBase) FindByName(name *string) (*entity.Board, error) {
	entity := entity.NewBoard()
	store := this.Context.Store
	ok, err := store.Query(T.BOARD).
		All().
    	Where(
    		T.BOARD_C_NAME.Matches(name),
    	).
    	SelectTo(entity);
    if err != nil {
    	return nil, err
    }
    if ok {
	    return entity, nil
    }
    return nil, nil
}
    
func (this BoardDAOBase) FindByDescription(description *string) (*entity.Board, error) {
	entity := entity.NewBoard()
	store := this.Context.Store
	ok, err := store.Query(T.BOARD).
		All().
    	Where(
    		T.BOARD_C_DESCRIPTION.Matches(description),
    	).
    	SelectTo(entity);
    if err != nil {
    	return nil, err
    }
    if ok {
	    return entity, nil
    }
    return nil, nil
}
    
