/**
 * WARNING: Generated code! do not change!
 * Generated by: go/EntityDAOBase.ftl
 */
package impl

import (
	"github.com/quintans/taskboard/common/entity"
	T "github.com/quintans/taskboard/biz/tables"
	"github.com/quintans/toolkit/web/app"
	coll "github.com/quintans/toolkit/collection"
)

type TaskDAOBase struct {
	Context *AppCtx
}

func (this TaskDAOBase) Delete(entity *entity.Task) error {
	store := this.Context.Store
	return app.Delete(store, T.TASK, entity)
}
	
func (this TaskDAOBase) DeleteById(id int64) (bool, error) {
	store := this.Context.Store
	return app.DeleteById(store, T.TASK, id)
}

func (this TaskDAOBase) DeleteByIdAndVersion(id int64, version int64) error {
	store := this.Context.Store
	return app.DeleteByIdAndVersion(store, T.TASK, id, version)
}
    
func (this TaskDAOBase) Save(entity *entity.Task) error {
	store := this.Context.Store
	return app.Save(store, T.TASK, entity)
}

func (this TaskDAOBase) FindById(id int64) (*entity.Task, error) {
	entity := entity.NewTask()
	store := this.Context.Store
	ok, err := app.FindById(store, T.TASK, entity, id)
	if ok {
		return entity, nil
	}
	return nil, err
}

func ConvertToTask(list coll.Collection) []*entity.Task {
	// converts the list to an array
	entities := make([]*entity.Task, list.Size(), list.Size())
	i := 0
	for e := list.Enumerator(); e.HasNext(); i++ {
		entities[i] = e.Next().(*entity.Task)
	}
	return entities
}

func (this TaskDAOBase) FindAll() ([]*entity.Task, error) {
	typ := (*entity.Task)(nil)
	store := this.Context.Store
	list, err := app.FindAll(store, T.TASK, typ)
	if err != nil {
		return nil, err
	}
	entities := ConvertToTask(list)
	return entities, nil
}
    
func (this TaskDAOBase) FindByPos(laneId *int64, position *int64) (*entity.Task, error) {
	entity := entity.NewTask()
	store := this.Context.Store
	ok, err := store.Query(T.TASK).
		All().
    	Where(
    		T.TASK_C_LANE_ID.Matches(*laneId),
    		T.TASK_C_POSITION.Matches(*position),
		).
		SelectTo(entity)
    if err != nil {
    	return nil, err
    }
    if ok {
	    return entity, nil
    }
    return nil, nil
}
    
