/**
 * WARNING: Generated code! do not change!
 * Generated by: go/EntityDAOBase.ftl
 */
package impl

import (
	"github.com/quintans/taskboard/common/entity"
	T "github.com/quintans/taskboard/biz/tables"
	"github.com/quintans/toolkit/web/app"
	coll "github.com/quintans/toolkit/collection"
)

type UserDAOBase struct {
	Context *AppCtx
}

func (this UserDAOBase) Delete(entity *entity.User) error {
	store := this.Context.Store
	return app.Delete(store, T.USER, entity)
}
	
func (this UserDAOBase) DeleteById(id int64) (bool, error) {
	store := this.Context.Store
	return app.DeleteById(store, T.USER, id)
}

func (this UserDAOBase) DeleteByIdAndVersion(id int64, version int64) error {
	store := this.Context.Store
	return app.DeleteByIdAndVersion(store, T.USER, id, version)
}
    
func (this UserDAOBase) Save(entity *entity.User) error {
	store := this.Context.Store
	return app.Save(store, T.USER, entity)
}

func (this UserDAOBase) FindById(id int64) (*entity.User, error) {
	entity := entity.NewUser()
	store := this.Context.Store
	ok, err := app.FindById(store, T.USER, entity, id)
	if ok {
		return entity, nil
	}
	return nil, err
}

func ConvertToUser(list coll.Collection) []*entity.User {
	// converts the list to an array
	entities := make([]*entity.User, list.Size(), list.Size())
	i := 0
	for e := list.Enumerator(); e.HasNext(); i++ {
		entities[i] = e.Next().(*entity.User)
	}
	return entities
}

func (this UserDAOBase) FindAll() ([]*entity.User, error) {
	typ := (*entity.User)(nil)
	store := this.Context.Store
	list, err := app.FindAll(store, T.USER, typ)
	if err != nil {
		return nil, err
	}
	entities := ConvertToUser(list)
	return entities, nil
}
    
func (this UserDAOBase) SoftDelete(entity *entity.User ) error {
	store := this.Context.Store
	return app.SoftDelete(store, T.USER, entity)
}
	
func (this UserDAOBase) SoftDeleteByIdAndVersion(id int64, version int64) error {
	store := this.Context.Store
	return app.SoftDeleteByIdAndVersion(store, T.USER, id, version);
}
    
func (this UserDAOBase) FindAllWithDeleted() ([]*entity.User, error) {
	typ := (*entity.User)(nil)
	store := this.Context.Store
	list, err := app.FindAllWithDeleted(store, T.USER, typ)
	if err != nil {
		return nil, err
	}
	entities := ConvertToUser(list)
	return entities, nil
}
    
func (this UserDAOBase) FindByActiveUser(username *string) (*entity.User, error) {
	entity := entity.NewUser()
	store := this.Context.Store
	ok, err := store.Query(T.USER).
		All().
    	Where(
    		T.USER_C_USERNAME.Matches(*username),
    		T.USER_C_DEAD.Matches(app.NOT_DELETED),
		).
		SelectTo(entity)
    if err != nil {
    	return nil, err
    }
    if ok {
	    return entity, nil
    }
    return nil, nil
}
    
