/**
 * Initialy Generated by: go/EntityDAO.ftl
 */
package impl

import (
	dao "github.com/quintans/taskboard/biz/entity"
)

var _ dao.IBoardDAO = &BoardDAO{}

func NewBoardDAO(appCtx *AppCtx) dao.IBoardDAO {
	this := BoardDAO{}
	this.Context = appCtx
	return this
}

type BoardDAO struct {
	BoardDAOBase
}
