/**
 * Initialy Generated by: go/EntityDAO.ftl
 */
package impl

import (
	dao "github.com/quintans/taskboard/biz/entity"
)

var _ dao.ILaneDAO = &LaneDAO{}

func NewLaneDAO(appCtx *AppCtx) dao.ILaneDAO {
	this := LaneDAO{}
	this.Context = appCtx
	return this
}

type LaneDAO struct {
	LaneDAOBase
}
