/**
 * Initialy Generated by: go/EntityDAO.ftl
 */
package impl

import (
	dao "github.com/quintans/taskboard/biz/entity"
)

var _ dao.ITaskDAO = &TaskDAO{}

func NewTaskDAO(appCtx *AppCtx) dao.ITaskDAO {
	this := TaskDAO{}
	this.Context = appCtx
	return this
}

type TaskDAO struct {
	TaskDAOBase
}
