/**
 * Initialy Generated by: go/EntityDAO.ftl
 */
package impl

import (
	dao "github.com/quintans/taskboard/biz/entity"
)

var _ dao.IUserDAO = &UserDAO{}

func NewUserDAO(appCtx *AppCtx) dao.IUserDAO {
	this := UserDAO{}
	this.Context = appCtx
	return this
}

type UserDAO struct {
	UserDAOBase
}

